x-app-common: &app-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  restart: always
  depends_on:
    - redis
    - rabbitmq
    - mariadb

services:

  web:
    <<: *app-common
    volumes:
      - ./staticfiles:/app/staticfiles:rw
    ports:
      - "127.0.0.1:8001:8000"
    command: poetry run gunicorn config.wsgi --bind 0.0.0.0:8000 --workers ${WORKERS} --log-level=debug --chdir=/app

  celery:
    <<: *app-common
    command: poetry run celery -A config worker -l INFO

  celery-beat:
    <<: *app-common
    command: poetry run celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"

  redis:
    image: redis:6
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  mariadb_data:
