# Generated by Django 5.1.5 on 2025-01-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("keycrm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="integration",
            options={
                "verbose_name": "Zenedu integration",
                "verbose_name_plural": "Zenedu integrations",
            },
        ),
    ]
