# Generated by Django 5.1.5 on 2025-04-24 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zenedu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("price", models.FloatField()),
                ("source_id", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("payment_system_type", models.CharField(max_length=20)),
                ("bot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="zenedu.bot")),
                ("subscriber", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="zenedu.subscriber")),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
