# Generated by Django 5.1.5 on 2025-05-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zenedu", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
