# Generated by Django 5.1.5 on 2025-05-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zenedu", "0003_subscriber_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_system_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
